name: GitHub pages

on: push

jobs:
  build:
    name: Build & Upload PDFs to GitHub pages
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install XeLaTeX
      run: sudo apt-get install texlive-xetex
    
    - name: Build PDFs
      run: |
        from build import main
        main()
      shell: python
    
    - name: Deploy Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: pdfs
