name: GitHub pages

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy PDFs to GitHub pages
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install XeLaTeX
      run: sudo apt-get install texlive-xetex
    
    - name: Build PDFs
      run: python3 build.py
    
    - name: Deploy Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: pdfs
