name: Release

on:
  push:
    tags:
      - *

jobs:
  build:
    name: Release PDFs
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install XeLaTeX
      run: sudo apt-get install texlive-xetex
    
    - name: Build PDFs
      run: python3 build.py release

    - name: Create release and Upload PDFs
      id: create_release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        file: "./pdf/*"
        prerelease: false
        file_glob: true
